# PYTHON
[[language]]
name = "python"
language-servers = [ "basedpyright", "ruff" ]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]


 # TYPESCRIPT / JAVASCRIPT
[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
language-servers = ["deno-lsp"]
auto-format = true

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
language-servers = ["deno-lsp"]
auto-format = true

[[language]]
name = "tsx"
roots = ["deno.json", "deno.jsonc", "package.json"]
language-servers = ["deno-lsp", "emmet-ls"]
auto-format = true

[[language]]
name = "jsx"
roots = ["deno.json", "deno.jsonc", "package.json"]
language-servers = ["deno-lsp", "emmet-ls"]
auto-format = true

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[language-server.deno-lsp.config.deno]
enable = true


# HTML / CSS / JSON
[language-server]
vscode-css-language-server = { command = "vscode-css-language-server", args = ["--stdio"], config = { provideFormatter = true, css = { validate = { enable = true } } } }
vscode-html-language-server = { command = "vscode-html-language-server", args = ["--stdio"], config = { provideFormatter = true } }
vscode-json-language-server = { command = "vscode-json-language-server", args = ["--stdio"], config = { provideFormatter = true, json = { validate = { enable = true } } } }
emmet-ls = { command = "emmet-ls", args = [ "--stdio" ]}
# biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "emmet-ls" ]
auto-format = true

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "emmet-ls" ]
auto-format = true


# JAVA
[[language]]
name = "java"
roots = ["pom.xml", "build.gradle", ]
language-servers = [ "jdtls" ]

[language-server.jdtls]
command = "~/.vscode/extensions/redhat.java-1.34.0-linux-x64/server/bin/jdtls"
